### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by zebapy** [theodoreb/eslint-config-drupal#1]
Drupal updated their js eslint config https://github.com/drupal/drupal/commit/ca9e5201e7a6619f23488ba058efd476979e2e93

**Comment by frob** [comment]
I just checked against 8.6.x and it looks to have been updated. This issue should be closed.

**Comment by frob** [comment]
Turns out this is missing a couple of changes from the issue queue, it also isn't extending eslint-config-airbnb with drupal depends on.
